---
title: "Personal Data"
author: "Duncan Gates"
date: "2/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      warning = F, 
                      message = F,
                      fig.align = 'center')
library(tidyverse)
library(lubridate)
library(here)
library(xml2)
library(data.table)
library(ggtext)
library(scales)
library(cowplot)

theme_fitness <- function() {
  theme_bw() %+replace%
  theme(text = element_text(family = "Montserrat"),
        plot.background = element_rect(fill = "black"),
        panel.background = element_rect(fill = "black"),
        # panel.grid.major.y = element_line(),
        # panel.grid.minor.y = element_line(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        plot.title = element_text(color = "white", hjust = 0.5))
}
```

## Data Structure

```{r}
fs::dir_tree(here("Data/apple_health_export/"))
```


## Data Import

```{r import}
records <- xml2::read_xml(here("Data/apple_health_export/export.xml"))
```

## Data Clean

```{r clean}
records2 <- xml_find_all(
  records,
  xpath = "
  .//Record[
         @type = 'HKQuantityTypeIdentifierHeartRate' and
         (starts-with(@endDate, '2019') or 
          starts-with(@endDate, '2020') or 
          starts-with(@endDate, '2021'))
      ]"
)

records3 <- xml_find_all(
  records,
  xpath = "//Record"
)
# New way to get all data
records_df <- XML:::xmlAttrsToDataFrame(xml["//Record"])

records_pivot <- records_df %>%
  mutate(value = as.double(value),
         row = row_number()) %>%
  pivot_wider(values_from = value, names_from = type) %>%
  select(-row)

unique(records_df$type)

records_tibble <- tibble(
  ts = records2 %>%
    xml_attr("endDate") %>%
    as.POSIXct(format = "%Y-%m-%d %H:%M:%S %z"),
  rate = records2 %>%
    xml_attr("value") %>%
    as.integer()
) %>%
  mutate(date_only = lubridate::date(ts)) %>%
  group_by(date_only) %>%
  mutate(mean_rate = mean(rate))
```

## Plots and Stuff

```{r plot1}
p <- records_tibble %>%
  ggplot(aes(x = ts, y = mean_rate)) +
  geom_jitter(alpha = 0.08, aes(y = rate), color = "#E3242B") +
  geom_line(color = "#7c0000", size = 1.85) +
  geom_smooth(color = "red", size = 3, method = "gam") +
  # geom_text(color = "white", size = 2, hjust = -0.05,
  #           x = records_tibble$ts[1], y = 95,
  #           family = "Montserrat",
  #           aes(label = "GAM Model\n Predictions")) +
  # geom_text(color = "white", size = 2, hjust = -0.05,
  #           x = records_tibble$ts[1], y = 128,
  #           family = "Montserrat",
  #           aes(label = "Daily Mean\nHeart Rate")) + # Why does this add so much time???
  scale_x_datetime(breaks = scales::pretty_breaks(n = 10)) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 8)) +
  labs(title = "Heart Rate over Time") +
  theme(text = element_text(family = "Montserrat"),
        plot.background = element_rect(fill = "black"),
        panel.background = element_rect(fill = "black"),
        # panel.grid.major.y = element_line(),
        # panel.grid.minor.y = element_line(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        plot.title = element_text(color = "white", hjust = 0.5))
cowplot::ggdraw(p) +
  geom_text(x = 0.05, y = 0.41, aes(label = "GAM Model\n Predictions"), family = "Montserrat", color = "red", size = 2.5) +
  geom_text(x = 0.05, y = 0.583, aes(label = "Daily Mean\nHeart Rate"), family = "Montserrat", color = "#7c0000", size = 2.5)
ggsave(here("Images/heart_rate.png"), bg = "black", width = 16, height = 9)
```

```{r plot2}
records_pivot %>%
  mutate(date = date(endDate)) %>%
  group_by(date) %>%
  summarise(steps = sum(HKQuantityTypeIdentifierStepCount, na.rm = T)) %>%
  ggplot(aes(x = date, y = steps)) +
  geom_line(color = "blue") +
  scale_y_continuous(labels = scales::comma, breaks = pretty_breaks(n = 10)) +
  labs(title = "Daily Sum of Steps") +
  theme(text = element_text(family = "Montserrat"),
        plot.background = element_rect(fill = "black"),
        panel.background = element_rect(fill = "black"),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        plot.title = element_text(hjust = 0.5, color = "white"))
ggsave(here("Images/DailySteps.png"), bg = "black", width = 16, height = 10)
```

```{r data-clean 2}
records_clean <- records_pivot %>%
  select(-HKQuantityTypeIdentifierHeight, -HKQuantityTypeIdentifierBodyMass) %>%
  rename(heart_rate = HKQuantityTypeIdentifierHeartRate,
         oxygen_saturation = HKQuantityTypeIdentifierOxygenSaturation,
         step_count = HKQuantityTypeIdentifierStepCount,
         distance_walking_running = HKQuantityTypeIdentifierDistanceWalkingRunning,
         basal_energy_burned = HKQuantityTypeIdentifierBasalEnergyBurned) %>%
  janitor::clean_names() %>%
  rename_with( ~ str_remove(., "hk_quantity_type_identifier_")) %>%
  rename(sleep_analysis = hk_category_type_identifier_sleep_analysis,
         apple_stand_hour = hk_category_type_identifier_apple_stand_hour,
         mindful_session = hk_category_type_identifier_mindful_session) %>%
  slice(-1,-2,-3)

# records_daily <- records_clean %>%
  # mutate(date = date(end_date)) %>%
  # group_by(date) %>%
#   rowwise() %>%
#   summarise(across(where(is.numeric)), ~sum(.x, na.rm = T))
```

```{r}
records_clean %>%
  # mutate(date = date(end_date)) %>%
  # group_by(date) %>%
  ggplot(aes(x = end_date, y = heart_rate_variability_sdnn)) +
  geom_line() +
  theme_fitness()
```

```{r}
ggplot(records_clean, aes(x = end_date, y = oxygen_saturation)) +
  geom_line(color = "goldenrod") +
  theme_fitness()
```


## Saving Data for Later

```{r}
write_rds(records_tibble, here("Data/heart_rate.rds"))
```

