---
title: "Running World Records"
author: "Duncan Gates"
date: "12/18/2020"
output: html_document
---

# Data Obtain

```{r include = F}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
library(rvest)
library(xml2)
library(tidyverse)
```

## Initial Data Scrape with rvest

Men's world records scrape.

```{r}
url <- "https://www.worldathletics.org/records/by-category/world-records"
mens_world_records <- url %>% 
  read_html() %>% 
  html_nodes(xpath='//*[@id="menoutdoor"]/table') %>% 
  html_table()
mens_world_records <- mens_world_records[[1]]
```

Women's world records scrape.

```{r}
womens_world_records <- url %>% 
  read_html() %>% 
  html_nodes(xpath='//*[@id="womenoutdoor"]/table') %>% 
  html_table()
womens_world_records <- womens_world_records[[1]]
```


https://en.wikipedia.org/wiki/Athletics_record_progressions for later bigger data obtain on each event.

## Data Cleaning

```{r}
mens_world_records <- mens_world_records %>% 
  select(Discipline, Perf, Competitor, DOB, Country, Date) %>%
  mutate(DOB = lubridate::dmy(DOB),
         Date = lubridate::dmy(Date)) %>%
  mutate(Perf = gsub("h #", "", Perf),
         Perf = str_remove(Perf, "h"),
         Perf = str_remove(Perf, "   *"),
         Perf = str_remove(Perf, "*"),
         Perf = str_remove(Perf, "   (i)"),
         Discipline = factor(Discipline),
         Country = factor(Country))

womens_world_records <- womens_world_records %>% 
  select(Discipline, Perf, Competitor, DOB, Country, Date) %>%
  mutate(DOB = lubridate::dmy(DOB),
         Date = lubridate::dmy(Date)) %>%
  mutate(Perf = gsub("h #", "", Perf),
         Perf = str_remove(Perf, "h"),
         Perf = str_remove(Perf, "   *"),
         Perf = str_remove(Perf, "*"),
         Perf = str_remove(Perf, "   (i)"),
         Discipline = factor(Discipline),
         Country = factor(Country))
```


## Basic Plotting

Running World Records

```{r}
mens_world_records %>% 
  slice(1:21) %>%
  slice(-15) %>% # SELECT OUT UNNECESSARY ONES
  ggplot(aes(x = Discipline, y = Perf)) + geom_text(aes(label = Competitor), size = 10)
```


```{r}

```



